/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as TeacherSessionSessionIdRouteImport } from './routes/teacher.session.$sessionId'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSessionSessionIdRoute = TeacherSessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/session/$sessionId': typeof TeacherSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/session/$sessionId': typeof TeacherSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/session/$sessionId': typeof TeacherSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/teacher'
    | '/session/$sessionId'
    | '/teacher/'
    | '/teacher/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/session/$sessionId'
    | '/teacher'
    | '/teacher/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/teacher'
    | '/session/$sessionId'
    | '/teacher/'
    | '/teacher/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  SessionSessionIdRoute: typeof SessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/session/$sessionId': {
      id: '/teacher/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/teacher/session/$sessionId'
      preLoaderRoute: typeof TeacherSessionSessionIdRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface TeacherRouteChildren {
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherSessionSessionIdRoute: typeof TeacherSessionSessionIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherSessionSessionIdRoute: TeacherSessionSessionIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  TeacherRoute: TeacherRouteWithChildren,
  SessionSessionIdRoute: SessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
